### ISSUE TITLE
Can't see all repos

### ISSUE THREAD

**Issue by mmcwatters** [simplerocket-llc/dear-cashew#1]
Basically, if our org has dozens of repos, but only A-G show up in Cashew, and I can't search beyond that.

**Comment by mmcwatters** [comment]
@hishboy yes, my org is authorized in Cashew. What's happening is that, of our many repos, those following "G" don't show up in the search to be added. Seems like there's a limit to the number of results in Cashew's search utility.

**Comment by hishboy** [comment]
Oh I see what you're saying. I'll take a look and see what's going on. Are you able to find your repository once you type in multiple characters?

Thanks for reporting this BTW

**Comment by mmcwatters** [comment]
No. Let's say the repo I'm searching for starts with "Road...." — other repos show up when I enter that into the search field, but for some reason not our own.

**Comment by hishboy** [comment]
found the issue. You should get a fix in the upcoming update i.e. v1.2

**Comment by mmcwatters** [comment]
Great, thanks!

**Comment by hishboy** [comment]
@mmcwatters - can you try searching with the following query: `dear-cashew user:simplerocket-llc`

`dear-cashew` is the repository name 
`simplerocket-llc` is the organization name

Can you try it with your repo/organization combo and let me know if you’re still not seeing it?

**Comment by hishboy** [comment]
@mmcwatters - you could also just search using `user:<Organization Name>` and that should list all organization repositories

**Comment by mmcwatters** [comment]
@hishboy searching for your repos works. searching for any repo above 'g' does not work for me in our own org

**Comment by hishboy** [comment]
I just updated repository search to return more results. Hoping that is enough to find your repositories. Please update cashew from app store  and let me know if it’s still an issue.

**Comment by mmcwatters** [comment]
Yes, that worked!



On July 14, 2016 at 9:32:31 PM, Hicham Bouabdallah (notifications@github.com)
wrote:

Closed #1 <https://github.com/simplerocket-llc/dear-cashew/issues/1>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/simplerocket-llc/dear-cashew/issues/1#event-723809117>,
or mute the thread
