### ISSUE TITLE
My profile pic doesn't show in the master view

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#11]
Notice how it shows your profile pic, but not mine

![/Users/ankushdharkar/Desktop/Screen Shot 2016-07-17 at 10.33.47 PM.png](http://content.cashewapp.io/api.github.com/ankushdharkar/20160718054134UTC/25a8cab2-f6fb-42d3-b097-9dea8ebd645e.png)

**Comment by hishboy** [comment]
The profile pic in the issue list shows the current assignee’s photo. The highlighted issue is Unassgined. That’s why you’re seeing a gray circle with the github logo inside. I’ll need to add a tooltip so it’s clearer to users. Thanks for pointing it out
