### ISSUE TITLE
Mark issues as read, but be shown when there's new activity

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#12]
There should be a way to quickly hide or show as dimmed the issues I already visited (for more than 3 seconds)  or until marked  read/seen/visited manually, until, something new happens on that issue!

This way, I can mark the issues I put out as read, and see them when you comment back on it

It should be a simple check-box on top “Hide all read” — 58 read issues, but not closed are not being shown — click here to show them

It would be a great feature to have

**Comment by hishboy** [comment]
I will add it to list of future enhancements.

**Comment by hishboy** [comment]
Added `Notifications` under main menu to accomplish this. Closing.
