### ISSUE TITLE
Unable to right-click and close my issues

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#13]
Unable to close an issue I created using the right-click context menu

![/Users/ankushdharkar/Desktop/Screen Shot 2016-07-17 at 10.51.52 PM.png](http://content.cashewapp.io/api.github.com/ankushdharkar/20160718055305UTC/e907dea7-c47a-428e-957f-02606d5ee136.png)

Btw, I can close this on Github directly

**Comment by hishboy** [comment]
Oops looks like it’s a bug
