### ISSUE TITLE
Edit comment does not work

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#15]
The option to edit a comment in the dropdown menu is disabled. This seems to be a bug

via [Cashew app](http://www.cashewapp.co)

**Comment by hishboy** [comment]
Were you trying to edit a comment on an issue that belongs to a repository you’re not a collaborator on? I’m guessing that’s the scenario since I have a bug that I’m trying to address around non-collaborator write access to an issue.

**Comment by ankushdharkar** [comment]
Yes, it’s a repository where I am not a collaborator. E.g, I cannot edit my comment in this issue

**Comment by hishboy** [comment]
Cool. I’m on it. It should be fixed in next Cashew update.
