### ISSUE TITLE
Need profile picture for Github user "simplerocket-llc"

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#17]
A profile picture should exist for the Github user `simplerocket-llc`
Otherwise, it feels like a spam account. No hard feelings

![/Users/ankushdharkar/Desktop/Screen Shot 2016-07-18 at 2.23.47 PM.png](http://content.cashewapp.io/api.github.com/ankushdharkar/20160718212448UTC/76d40150-13f0-4879-8b73-71c1000fbc57.png)

via [Cashew app](http://www.cashewapp.co)

**Comment by hishboy** [comment]
Good point. Updated. Thanks!
