### ISSUE TITLE
Advanced filters

### ISSUE THREAD

**Issue by visini** [simplerocket-llc/dear-cashew#2]
Would be great if we can filter by advanced tags:

https://github.com/blog/1866-the-new-github-issues

https://help.github.com/articles/searching-issues/#search-by-the-labels-on-an-issue

Eg. type `-label:bug` which will show all issues which do not have the label "bug".

**Comment by hishboy** [comment]
👍🏼 love it. We will definitely look into it

**Comment by hishboy** [comment]
@visini - I just added the following `NOT	 logic to Cashew search bar. It’s still not in the Mac App Store. I will ping you once it’s live.

1. `-assignee:<username>`
2. `-author:<username>`
3. `-mentions:<username>`
4. `-milestone:<milestone title>`
5. `-repo:<repo name>`
6. `-label:<label name>`

Please let me know if you need other search filters. We are planning to add the ability for users to create their own filters in the near future. More on that in the coming releases.
