### ISSUE TITLE
Better scollbars for the Dark theme

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#21]
The current scrollbars stand out too much from the rest of the app and are a little unappealing. They need to be subtle

via [Cashew app](http://www.cashewapp.co)

**Comment by hishboy** [comment]
Can you send me a screenshot of what you’re seeing? I personally turn off scrollbars system wide.

**Comment by ankushdharkar** [comment]
![/Users/ankushdharkar/Desktop/Screen Shot 2016-07-18 at 8.40.37 PM.png](http://content.cashewapp.io/api.github.com/ankushdharkar/20160719034059UTC/12b8be0d-adda-47be-801e-1918426dd90b.png)

**Comment by hishboy** [comment]
fixed!
