### ISSUE TITLE
[Bug] Unable to login

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#24]
I was using the app, when it automatically logged me out and showed me the screen to sign in. I am entering my correct username and password (I verified after logging in on the site), but it still won't work on the app

**Comment by hishboy** [comment]
I did have an issue where the app was randomly logging out folks due to API rate limits. I fixed a bunch of those issues in version 1.3. Still not completely done. Are you up-to-date with Cashew on the Mac App Store?

**Comment by ankushdharkar** [comment]
There are no updates for Cashew in the app store for me, but the About Cashew says `Version 1.2 (14)`

Also, I did add a lot more repositories, which are still syncing, so you may be spot on regarding the API rate limit

**Comment by hishboy** [comment]
Weird. Here’s what I’m seeing in the app store. Checkout version on the right hand side. Maybe try Commad+R on Cashew page or maybe close and re-open Mac App Store 

![image](http://content.cashewapp.io/github/hishboy/20160720024850UTC/f5054ea0-b4d3-49cf-8d4f-d96657419698.png)

**Comment by hishboy** [comment]
Added more fixes in Release 1.4 to minimize API requests.

**Comment by ankushdharkar** [comment]
My app store page looks the same. It's the version number in the app's About Cashew that reports `1.2`

![screen shot 2016-07-20 at 10 02 11 am](https://cloud.githubusercontent.com/assets/1935403/16995489/8ce66eb8-4e61-11e6-8c92-55dba5764fed.png)


![screen shot 2016-07-19 at 8 15 19 pm](https://cloud.githubusercontent.com/assets/1935403/16995384/e8e442f4-4e60-11e6-871c-247d8102ad59.png)

**Comment by hishboy** [comment]
Do you see collapse/expand triangles next to repositories? see screenshot. If so, that means you’re using v1.3. Otherwise, I wonder if you have to manually update by going to the **Update** tab on Mac App Store


![image](http://content.cashewapp.io/github/hishboy/20160721022723UTC/67c1faf1-c2f1-4e1e-abf0-f63101180cd5.png)

**Comment by ankushdharkar** [comment]
No, I don’t see the triangles

I went to the Updates tab, but there is nothing to update

**Comment by ankushdharkar** [comment]
Let me know when the `1.4` shows up in store. I’ll uninstall and reinstall then if needed

**Comment by hishboy** [comment]
👍🏼

**Comment by hishboy** [comment]
@ankushdharkar 1.4 is in the app store. Give it a shot! Super thanks for all your feedback.

**Comment by ankushdharkar** [comment]
@hishboy: My pleasure :) 

I just updated the app, and it’s now `1.4`. You’ve been a busy bee. So many things have been fixed. You’re rockin’ it!

**Comment by hishboy** [comment]
All thanks to you! 🙏🙏🙏
