### ISSUE TITLE
[Feature] Add likes and other reactions to comments

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#25]
The ability to like and add other reactions to the comments, as done on Github’s website

![/Users/ankushdharkar/Desktop/Screen Shot 2016-07-19 at 7.45.20 PM.png](http://content.cashewapp.io/api.github.com/ankushdharkar/20160720024631UTC/8ba2bdd6-d6cc-4d63-b4e7-13b5556f8679.png)

**Comment by ankushdharkar** [comment]
Great job @hishboy! Was waiting for this one :)

**Comment by hishboy** [comment]
Thanks! It’s still not released to the app store. I’ll ping you once it’s in.

**Comment by hishboy** [comment]
@ankushdharjar - `1.9` in app store with reactions :)

**Comment by ankushdharkar** [comment]
Can we have the reactions show up on hovering, instead of clicking the smiley button? Thanks

**Comment by hishboy** [comment]
definitely.
