### ISSUE TITLE
[Bug] New issue in private repo doesn't show up in Cashew

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#28]
I ❤️ that we can now see milestones in the repos. That’s really cool 🎊

I created a new issue and a new milestone in one of my private repos. The milestone showed up in cashew, but the issue didn’t

I quit the app and reopened it, but still no luck

**Comment by hishboy** [comment]
Interesting. Did you create the issue in Cashew or Github.com? Also, is the sync  spinner running for you?

**Comment by hishboy** [comment]
Also, can you try searching in the search bar? i.e. `#<issue number>` . Does that return anything?

**Comment by hishboy** [comment]
Looks like things got out of sync for some reason. I’ll take a look. Thanks

**Comment by ankushdharkar** [comment]
@hishboy: Do you think it may have something to do with `private` repos?

**Comment by hishboy** [comment]
If you’re able to see other issues in that private repo, that means there’s a syncing issue. 

I use private repositories as well and never encountered this issue so that’s why I’m thinking it’s related to syncing

**Comment by ankushdharkar** [comment]
@hisboy: Just created another issue there, it doesn’t show up either

**Comment by hishboy** [comment]
I’m guessing you created another issue on Github.com and tried a force sync?

Have you tried creating a new issue on Cashew on that same repo? Does it show up?

**Comment by ankushdharkar** [comment]
Will try that now 

Btw, I removed both repos from Cashew and added them back. Still the issues don't show up 😞

**Comment by ankushdharkar** [comment]
The newly created issue from Cashew shows up, with the correct next issue number

**Comment by hishboy** [comment]
Oh that’s super interesting because removing and adding repo again does a full fresh sync. Been trying it here with a private repo and I’m unable to reproduce. I’ll keep trying.

**Comment by ankushdharkar** [comment]
I just downloaded Cashew afresh, and got the version `1.5`. In that repo, the issue #3 that I created from Cashew shows up, but #1 and #2 don’t

**Comment by hishboy** [comment]
😞 bummer. I’ll keep looking into it.

**Comment by hishboy** [comment]
Guessing this is fixed? Please reopen if otherwise

**Comment by ankushdharkar** [comment]
This is fixed. Thank you 🙌  !
