### ISSUE TITLE
How does the Drafts feature work?

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#29]
If I don’t put a repository name when creating an issue, it doesn’t let me save it. After that, there are only two options: `Create` and `Discard`

**Comment by hishboy** [comment]
For now, only comments on existing issues land in Drafts.  I’m still working on adding new issues in drafts.

**Comment by ankushdharkar** [comment]
I am still unclear on the comments part. Are you saying if I start writing a comment and go visit something else  without hiting `Discard` or `Comment`, it goes into the `Drafts`? 

Just tried this theory, it didn’t work

**Comment by hishboy** [comment]
Check this video out. It’s not working for you?

[Demo Video.mov](http://content.cashewapp.io/api.github.com/hishboy/20160726025437UTC/554fcbed-7d6f-4786-b2a4-98c97d99f1f9.mov)

**Comment by ankushdharkar** [comment]
Wow. Just checked out the video. That's cool. And ❤️  the ⭐  favorites! 

No, that's not how it's for me now. I am on version `1.4`

**Comment by ankushdharkar** [comment]
Ok, I have `1.5` now. And the drafts **don’t** work as shown in your video

**Comment by hishboy** [comment]
Is it not saving at all?

**Comment by ankushdharkar** [comment]
Nope

**Comment by hishboy** [comment]
Do you mind running the following command from Terminal and paste the results?
`sqlite3 /Users/hicham/Library/Containers/com.simplerocket.Issues/Data/Documents/database/issues.db "SELECT * FROM app_settings”`

**Comment by ankushdharkar** [comment]
![/Users/ankushdharkar/Desktop/Screen Shot 2016-07-25 at 8.51.00 PM.png](http://content.cashewapp.io/api.github.com/ankushdharkar/20160726035136UTC/509bd7df-4ade-47ed-ba34-c20af29d83fe.png)

**Comment by hishboy** [comment]
Looks like the closing quote is not correct. Wanna paste the text again? I just updated one more time

**Comment by ankushdharkar** [comment]
![/Users/ankushdharkar/Desktop/Screen Shot 2016-07-25 at 8.53.35 PM.png](http://content.cashewapp.io/api.github.com/ankushdharkar/20160726035348UTC/0ee35179-507c-452c-81c6-c649015fec9b.png)

**Comment by hishboy** [comment]
You need to have Cashew app closed. Sorry forgot to mention it.

**Comment by hishboy** [comment]
It should print something like this 


![image](http://content.cashewapp.io/github/hishboy/20160726035517UTC/53b8c114-1d71-488d-bc56-c434d05f77b3.png)

**Comment by ankushdharkar** [comment]
![screen shot 2016-07-25 at 8 59 14 pm](https://cloud.githubusercontent.com/assets/1935403/17125714/b9fc664e-52aa-11e6-921e-e5764a8d9677.png)

**Comment by hishboy** [comment]
oh wow. looks like for some reason your database is stuck at version 7 instead of 16. My advise is to dump your database and run Cashew again. That’s why you’re seeing a bunch of problems with new features. 

I need to find a better way to address this in the future. In the meantime, can you do the following:

1.  Completely close Cashew app
2. Run the following command `rm -rf /Users/$USER/Library/Containers/com.simplerocket.Issues/`
3. Open Cashew again. It will ask you to login.

**Comment by ankushdharkar** [comment]
I did the above steps. The problem did not solve, or rather, new problems emerged

After using `rm -rf /Users/$USER/Library/Containers/com.simplerocket.Issues/`, I did login and see all 3 of the issues in the private repo. 

But soon afterwards, while trying to sync all my repos, the app hung often. After quitting it, I was unable to log in for sometime. Maybe I ran out of API limit or something

One thing I did note is, running that `sqlite3` command still returns: `db.schema.version|7` (like before)

**Comment by hishboy** [comment]
I just submitted a new version to the app store to address the database corruption problem. I’ll ping you once v1.6 is available in the Mac App Store

**Comment by ankushdharkar** [comment]
The app is completely busted now. I removed it using the App cleaner, ran `rm -rf /Users/$USER/Library/Containers/com.simplerocket.Issues/`, restarted my laptop, reinstalled it from the store

Now it shows issues during the first sync as a running list, but when I click any repo, everything in the issues list disappears

I know `1.6` is on it's way. Just wanted to update you on what's happening for any future debugging

**Comment by hishboy** [comment]
Good to know. What do you have the sorting set to? `DATE MODIFIED`?

**Comment by ankushdharkar** [comment]
Yes

**Comment by hishboy** [comment]
hmm I’ll keep an eye on it. Hoping 1.6 gets in the app store tomorrow 

![Fingers crossed](https://media.giphy.com/media/l3UcjBJUov1gCRGbS/giphy.gif)

**Comment by hishboy** [comment]
v1.6 is in the Mac App Store. Grab it and let me know if you’re still encountering issues.

**Comment by ankushdharkar** [comment]
@hishboy: Good work sir!

The update showed up in the app store this time! 🎉🎊

Initially, it did the same thing where clicking a repo would still say _No Issues Found_, but then I deleted all the repos, and added them again, and it seems to be working now! Hurray!

**Comment by ankushdharkar** [comment]
How did you fix it?

**Comment by ankushdharkar** [comment]
Drafts bug

**Comment by hishboy** [comment]
Perfect! I just made sure the local database schema was at db_version=16 which in your case was stuck at db_version=7
