### ISSUE TITLE
Drag & drop file upload

### ISSUE THREAD

**Issue by visini** [simplerocket-llc/dear-cashew#3]
In the Web UI we can simply drag & drop any supported file into the text area, and it will upload & place a link.

While it shows a green border while dragging a file over the text area, it does not currently appear to be working – I suspect a bug. Can anyone confirm this is working as of now?

**Comment by hishboy** [comment]
![/Users/hicham/Downloads/56b822a763353815b0050000.png](http://content.cashewapp.io/api.github.com/hishboy/20160708183827UTC/454e9287-2111-4347-b07b-b58da8c2952c.png)


Just tested it (see above). We only allow image files. Guessing you’re uploading a non-image?

**Comment by hishboy** [comment]
If that’s the case, which file format are you interested in attaching? would love to add it to a future update.

**Comment by visini** [comment]
Ok I can confirm this on my end. I tried uploading an excel spreadsheet (xlsx).

**Comment by hishboy** [comment]
Version 1.2 will support the same list of files as Github. See list of supported fileS:

1 PNG (.png)
2. GIF (.gif)
3. JPEG (.jpg)
4. Microsoft Word (.docx), Powerpoint (.pptx), and Excel (.xlsx) documents
5. Text files (.txt)
6. PDFs (.pdf)
7. ZIP (.zip, .gz)

**Comment by hishboy** [comment]
@visini you should be able to upload more than images now(see above list). Hit me up if you’re still unable to upload spreadsheets.

Note: Update Cashew from the app store
