### ISSUE TITLE
How to use notifications in Cashew

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#30]
My notifications don’t seem to work. Haven’t gotten a single notification from Cashew about any new comment

**Comment by hishboy** [comment]
It should just work automatically. Doesn’t sound it is #fail :) 

Can you go to System `Preferences > Notifications` and tell me if you see Cashew? (see screenshot)


![image](http://content.cashewapp.io/github/hishboy/20160726023300UTC/f529b522-7d1b-43ce-9ea3-1ba78a468066.png)

**Comment by hishboy** [comment]
It should just work automatically. Doesn’t sound it is #fail :) 

Can you go to System `Preferences > Notifications` and tell me if you see Cashew? (see screenshot)


![image](http://content.cashewapp.io/github/hishboy/20160726023356UTC/85f8dd0a-9f63-4396-999e-02ec72578f7f.png)

**Comment by hishboy** [comment]
Also, do you have `Web`  selected under Github.com > Settings > Notifications (see screenshot below)


![image](http://content.cashewapp.io/github/hishboy/20160726024139UTC/2c7a562e-47f2-41d7-998b-53238d4234f4.png)

**Comment by ankushdharkar** [comment]
I think everything looks like how you showed in the screenshots: 

![screen shot 2016-07-25 at 7 44 11 pm](https://cloud.githubusercontent.com/assets/1935403/17124477/3e839e7e-52a0-11e6-99a5-1e20c5180c96.png)

![screen shot 2016-07-25 at 7 45 13 pm](https://cloud.githubusercontent.com/assets/1935403/17124491/542bebfa-52a0-11e6-9a3a-5ad81a60a250.png)

**Comment by hishboy** [comment]
What version of Cashew do you have? 1.4 or 1.5? I would recommend grabbing 1.5. v1.4 has a bug where notifications get erased after 10 seconds.

Couple other questions:

1. when you look at  the Notifications in sidebar? Do you see anything there?
2. Check macOS Notification Center. Do you see any notifications from Cashew?


![image](http://content.cashewapp.io/github/hishboy/20160726025122UTC/af11ad80-7065-470a-85c3-e83254f03fc0.png)

**Comment by ankushdharkar** [comment]
I am on `1.4`. Same thing again. I see there is `1.5` in the store, but I can't update

![screen shot 2016-07-25 at 7 56 04 pm](https://cloud.githubusercontent.com/assets/1935403/17124699/dbea0bfc-52a1-11e6-97b3-1f805d029e80.png)

1. I don't see anything in the Notifications on the sidebar in Cashew
2. I don't see any notifications from Cashew in the OS X Notification Center on the right

**Comment by hishboy** [comment]
Ugh. That’s annoying. You can force the app store to give you 1.5 by uninstalling the app and installing again

**Comment by ankushdharkar** [comment]
Will I lose the repos I have already added?

**Comment by hishboy** [comment]
The repo list gets synced to iCloud so you won’t lose anything when you reinstall but you still need to resync all the issues from Github.com

**Comment by hishboy** [comment]
OR you can restart your computer and hope macOS fixes your issue

**Comment by ankushdharkar** [comment]
Maybe app store batches apps to be updated?

**Comment by ankushdharkar** [comment]
I am now on `version 1.5(18)`, yet not receiving any notifications. Maybe when I restart my computer, it will fix it?

**Comment by hishboy** [comment]
Checkout my comment on #29

**Comment by ankushdharkar** [comment]
This seems to be working now, haven't been able to verify it properly yet. If it comes up again, I'll reopen this
