### ISSUE TITLE
[Feature] New update to Cashew is now available

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#31]
It would be nice to have a message show up in a top bar (that can be dismissed), which let’s us know that there is a new version in the store, with a [link](https://itunes.apple.com/us/app/cashew/id1126100185?mt=12) to open up the Cashew’s page on the app store and update it

**Comment by hishboy** [comment]
❤️ it

**Comment by hishboy** [comment]
Added menu item to check for new cashew version


![image](http://content.cashewapp.io/github/hishboy/20160814020600UTC/224f4f8b-fa01-41d3-9d38-13fb645c8d14.png)

**Comment by hishboy** [comment]
Apple rejected my app because of this feature. Refering to “Check For Updates” menu item above so I had to remove it :(

**Comment by ankushdharkar** [comment]
What if it happens in the background once a day? Is that also against their policies?

**Comment by hishboy** [comment]
yep it is. The policy states only Mac App Store can show updates to app. :/ 


![gif](http://media0.giphy.com/media/3XEgV9kfwLy1i/giphy.gif)

**Comment by ankushdharkar** [comment]
Well, that has been failing consistently recently :/
