### ISSUE TITLE
Remove from Drafts

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#34]
I am unable to delete drafts from the Drafts list

Clearing the text box doesn’t work for discarding the draft (it ends up remembering a single character from the last typed)

Sometimes, I may _not_ want to send out a particular draft I was writing, because someone else may comment the same thing, or if it’s no longer valid

**Comment by hishboy** [comment]
I found this bug last night. Should be fixed in next update. One workaround with current version is to leave a character in the text field and then click on `Discard` button. That should force a delete
