### ISSUE TITLE
[Bug] Favorites has some problems

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#36]
The favorites aren’t working as expected. Sometimes, on favortiting, some other issue gets favorited instead

Removing favorites has the same problem

![/Users/ankushdharkar/Desktop/Cashew.gif](http://content.cashewapp.io/api.github.com/ankushdharkar/20160727171938UTC/c35cd89c-8d82-44f0-9e0a-d10797c0ce39.gif)

**Comment by hishboy** [comment]
Looks like there is a delay on selection. It favorited the last issue right before you selected the first one. I see the issue now. Should be next in the upcoming update.
