### ISSUE TITLE
[Feature Request] Ability to see ALL the issues

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#39]
When you start the app the first time, it shows you issues from all the repos, but once you select an option on the sidebar, there's no way of seeing **all** the issues again. Can we have an ALL option for this please?

**Comment by hishboy** [comment]
For sure. One way to do it is to clear the search bar but maybe I should just add an All option under `Main Menu`

**Comment by ankushdharkar** [comment]
I like the idea of having it in the main menu
