### ISSUE TITLE
While editing, changes are lost when accidentally selecting another issue from the list

### ISSUE THREAD

**Issue by visini** [simplerocket-llc/dear-cashew#4]
Maybe display an alert or warning?

**Comment by hishboy** [comment]
We’re planning on just adding a Drafts feature. Basically, we’ll store your comment as a draft until you save or discard the comment.

**Comment by hishboy** [comment]
@visini comments are now auto-saved until to manually discard or save. Grab the latest update and let me know if it’s not working for you.
