### ISSUE TITLE
Renaming/Editing a milestone does't update on Cashew

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#51]
I know this is not a very usual case. But maybe with time, it will be nice to get things to update on frontend (or at least on hitting the manual refresh)

**Comment by hishboy** [comment]
Bummer. I thought I fixed that. Can you try restarting Cashew and see if that resolves it? I’ll work on fixing it to next release.

**Comment by hishboy** [comment]
found the issue. Fixed it for `1.9` 

Still waiting on Apple to review `1.8`. Definitely taking their time on that 😕

**Comment by ankushdharkar** [comment]
Thank you. Restarting the app fixed it for now

🍏  being 🍎 ?

**Comment by hishboy** [comment]
![gif](http://media2.giphy.com/media/26FxGPtjnVeS6qiJ2/giphy.gif)
