### ISSUE TITLE
Discovering *what* you can search for is really hard

### ISSUE THREAD

**Issue by ricburton** [simplerocket-llc/dear-cashew#52]
There’s no clear way to learn which search tags I can use for what. I would love some UI that showed me what kinds of things I can type and added them in. For example: https://cl.ly/1E240N140a3I

**Comment by hishboy** [comment]
Agreed, trying to workout a clean UI to do it. Thanks for the feedback.

Meanwhile, here’s the list of search tags:
 -   Issue State `is:closed` or `is:open`
 -   Assignee `assignee:hishboy`
 -   Author `author:hishboy`
 -   Mentions`mentions:hishboy`
 -   Repositories `repo:hishboy/issues-osx`
 -   Milestones `milestone:”Milestone v0.1”`
 -   Labels `label:"source list”`
 -  Issue Number `#123`
 -  Any query string

You can also negate the search by adding a `-` i.e. if you want to search for all issues that don’t have “bug” label, you can do this `-label:bug`

**Comment by hishboy** [comment]
@ricburton - what’s coming in `1.10`


![image](http://content.cashewapp.io/github/hishboy/20160828191425UTC/0ecbdc87-1bb6-47e6-951b-89f4168cf013.png)

**Comment by hishboy** [comment]
`1.10` is released. Give it a shot!
