### ISSUE TITLE
Recreating the Github filter style would be great

### ISSUE THREAD

**Issue by ricburton** [simplerocket-llc/dear-cashew#54]
I am really used to closed issues being hidden by default. The UI here is something I’m very used to: https://cl.ly/2K1A073I092w

Perhaps something like this could work in the app?

Also, only using icons often causes customers lots of issues. We ran into a few issues around this. Icons + text are generally the best :)

https://cl.ly/0i353i472r0r
http://uxmyths.com/post/715009009/myth-icons-enhance-usability

**Comment by hishboy** [comment]
You should be able to only allow Open issues in Preferences. Assuming you have `1.7` installed (see screenshot)


![image](http://content.cashewapp.io/github/hishboy/20160810033558UTC/75c7c5cf-880e-4b14-96dd-d06c865eb78f.png)
