### ISSUE TITLE
Some organization repos don't show up in search

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#6]
I am using Cashew- Version 1.2 (14)

I am trying to add some of my repos to Cashew, but I am unable to find many repos belonging to an organization `abc-xyz` (Organization name has a hyphen in it, which also makes the search's autocomplete unreliable) 

I have authorized Cashew to access my organization as suggested [here](http://www.cashewapp.co/help/private_organization_repositories) and most repos in the organization do show up on search, just some don't. I have owner level access to all of them

I used the tricks suggested in #1 : [\<repo-name\> user:\<organization-name\>](https://github.com/simplerocket-llc/dear-cashew/issues/1#issuecomment-232113117) and [user:\<organization-name\>](https://github.com/simplerocket-llc/dear-cashew/issues/1#issuecomment-232113761), and it lets me see the missing repos

This seems like a bug. Let me know if I can help

**Comment by ankushdharkar** [comment]
Just found this to be the case with a public repo as well. Try adding: `ebryn/ember-component-css`

**Comment by hishboy** [comment]
Found the issue. Basically, searching using `<org name>/<repo name>` doesn’t really work. The current search only works with `<repo name>`. 

Thanks for pointing it out. I found a fix. It will be addressed in next Cashew version.

**Comment by ankushdharkar** [comment]
@hishboy: Then why was it that some repos in typinh just the org `abc-xyz` showed up, while some didn’t?

**Comment by hishboy** [comment]
Are they showing up as part of the organization name or the repo name? So when I search `abc-xyz`, I do get results back but it’s matching against repository name. 

I’m guesing you have another example where this is not true?

**Comment by ankushdharkar** [comment]
My organization is private. So, you won't be able to see it. It's work stuff. Sorry for the confusion

The example is more of `<organization-name>/<repo-name>`

**Comment by hishboy** [comment]
fixed so `<organization-name>/<repo-name>` syntax is handled correclty
