### ISSUE TITLE
[Bug] Lost all my repos on a fresh install

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#62]
I was unable to update to `1.9` because the App Store said that I already had it installed, but the `About Cashew` would say I have `1.8`

Long story longer, I removed the app, and reinstalled it. When the app started, I had lost most of my repos in the `Repositories` list. I thought they were backed up to my iCloud settings and would restore in the fresh install, but that didn’t happen. Any way to rollback?

**Comment by hishboy** [comment]
Sorry, I actually botched the synching code in `1.8` which is why you’re not seeing the repos. Working on a fix ASAP. 

Again, sorry for the frustration.

**Comment by ankushdharkar** [comment]
Np :)

**Comment by hishboy** [comment]
@ankushdharkar - I did some work in `1.10` to make sure you don’t lose Repository between installs + prevented maxing out github API limits. 

Want to grab the latest version and let me know if you encounter any issues?
