### ISSUE TITLE
Saved search for "Unassigned"?

### ISSUE THREAD

**Issue by gabek** [simplerocket-llc/dear-cashew#64]
Is there a way to create a saved search for Unassigned items?  I've tried different variations, but have been unable to come up with the right recipe.  Thanks!

**Comment by hishboy** [comment]
Not at the moment. I’ll fix for next Cashew update.

**Comment by hishboy** [comment]
Adding ` no:label`, ` no:assignee` and ` no:milestone` in next version of Cashew

**Comment by hishboy** [comment]
`1.10` is out. Grab it. It should have ` no:label`, ` no:assignee` and ` no:milestone`

**Comment by gabek** [comment]
Works great, thanks again!
