### ISSUE TITLE
crash on launch, version 1.10

### ISSUE THREAD

**Issue by chrismccoy** [simplerocket-llc/dear-cashew#67]
still hasnt solved the issue with crashing with latest update 

https://gist.github.com/anonymous/d129f9307f66cdc102013319a69a85e1

here is the dump from the error.

**Comment by hishboy** [comment]
Looking into it. Sorry for the inconvenience

**Comment by hishboy** [comment]
@chrismccoy - Would it be possible for you to send me a copy of this directory /Users/$USER/Library/Containers/com.simplerocket.Issues/Data/Documents/database zipped up? That would help us get the the bottom of the issue

**Comment by hishboy** [comment]
You could also try delete this directory while the app is closed  i.e.

`rm -rf /Users/$USER/Library/Containers/com.simplerocket.Issues/Data/Documents/database`

**Comment by chrismccoy** [comment]
tried removing that file, opened the app, asked me to login to github again, but then crashes.

here is the db dir zipped

[db.zip](https://github.com/simplerocket-llc/dear-cashew/files/463232/db.zip)

**Comment by hishboy** [comment]
Thanks. Still not seeing the crash on my side. I do see it come in via Crashlytics though. One last thing to try:

1. Close Cashew and completely uninstall it. i.e. remove from Applications
2. Delete the following directory
`rm -rf /Users/$USER/Library/Containers/com.simplerocket.Issues`
3. Reinstall the app from Mac App Store. Are you still hitting the crash?

**Comment by hishboy** [comment]
I also submitted `1.10.1` to add some logging around the crash + fix some potential issues. I’ll ping you once it hit the App Store.

**Comment by chrismccoy** [comment]
tried removing the container dir, still crashing

**Comment by hishboy** [comment]
@chrismccoy - `1.10.1` is in the Mac App Store. Do you mind installing it and running Cashew? If it crashes can you run it one more time so Crashlytics can send me the logs? Thanks in advance.

**Comment by chrismccoy** [comment]
crashed again, loaded it twice, let me know.

**Comment by hishboy** [comment]
Hello! you mind grabbing the latest version from the mac app store and see if it’s still crashing for you. I believe I fixed the issue and also added a lot more logging around the code in case it’s still crashing.

**Comment by chrismccoy** [comment]
so far so good its not crashing

**Comment by hishboy** [comment]
perfect. Thanks for your help debuging this bug. Let me know if you hit any other issue sor have some feature requests

**Comment by chrismccoy** [comment]
having other issues though, its removing added repos i have in the client, when i load up the client again its missing all the repos i added, asking me to select some repos to add to the client, and its pinwheel freezing once trying to add

**Comment by chrismccoy** [comment]
also when i do add a repo, all the issues show up, when the sync is finished, all the issues disappear

**Comment by hishboy** [comment]
I wonder if the app got into a bad state due to all those crashes during launch. Lets try clearing the local cache and see if that fixes things for you:

1. Close Cashew app completely 
2. Open Terminal and paste the following `rm -rf /Users/$USER/Library/Containers/com.simplerocket.Issues/Data/Documents/database`
3. Run Cashew again. It will ask you to login and possibly ask you to select new repos. Pick one to start with and wait for the synching to finish
4. Once the synching is done. Close Cashew and open it. 

Let me know if it’s still broken

**Comment by chrismccoy** [comment]
tried doing that, didnt ask me to readd repos though, i even deleted the app completely with clean my mac, and reinstalled from the appstore, synced, and the repo has disappeared saying no issues.

**Comment by hishboy** [comment]
you mind trying one more time by following the same steps above? Your repositories were marked deleted on CloudKit due to original launch crash.

**Comment by chrismccoy** [comment]
seems to be fine now, but when you add a repo is it suppose to add all the tagged branches as well with the issues? cause its only adding the master

**Comment by hishboy** [comment]
Cool. The app actually doesn’t use any branches. It only looks at Issues. (similar to issues tab on github.com) 

Glad to hear things are working now.
