### ISSUE TITLE
Disable non-contributors to enter Milestone, Assignees, Labels on Cashew app

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#8]
When creating a new issue using Cashew’s `+ NEW ISSUE` button, it lets you enter in Milestone, Assignees and Labels, even when you are not a collaborator. 

This information is dropped when the issue gets created on Github though

To avoid confusion, these options to enter extra information should be disabled with a `?` explaining why (or maybe not even exist)

**Comment by hishboy** [comment]
👍🏼 Will do!
