### ISSUE TITLE
Doesn't work on High Sierra

### ISSUE THREAD

**Issue by morygonzalez** [simplerocket-llc/dear-cashew#89]
Cashew gets hang up on start up. Although I tried uninstall and reinstall, it didn't make sense. Please solve this issue 🙏🏻

**Comment by kMikaZu** [comment]
Same here. is this app still maintained? Seems awful quiet here...

**Comment by hishboy** [comment]
The app is no longer maintained by SimpleRocket LLC. We’re planning to open source it in the next week or so. This way folks can go in fix those issues and we’ll release the app on a biweekly bases if enough fixes are available.

Follow the twitter handle for updates on open sourcing the app. ‘@cashewappco’

**Comment by hishboy** [comment]
https://github.com/simplerocket-llc/OpenCashew

**Comment by kMikaZu** [comment]
Ok, I hope that the open source community will get vividly for this project!
