### ISSUE TITLE
Create new issue on Github website directly using more features

### ISSUE THREAD

**Issue by ankushdharkar** [simplerocket-llc/dear-cashew#9]
Github website's own issue creator is more feature-rich. It would be nice to have a button in Cashew, which opens up a webpage to create the new issue in your browser: `https://github.com/<user-name>/<repo-name>/issues/new`

Example: [Create new issue for this repo](https://github.com/simplerocket-llc/dear-cashew/issues/new)

**Comment by hishboy** [comment]
I would like to improve Cashew’s issue creator so would love to hear what features you feel are missing and I’ll make sure to address them in future releases.

**Comment by ankushdharkar** [comment]
I initially thought of writing it down here, but then realized that most of the time, we don't create new issues, so it may be simpler to go to the website

Anyway, things I would like:

- Preview of the markdown
- Helper buttons to insert link, insert code, reference issue with autocomplete, change size of text, etc
- A sample showing different examples of markdown effects and how to achieve them

**Comment by hishboy** [comment]
Perfect. Will definitely incorporate that. Thanks again!

**Comment by ankushdharkar** [comment]
**Love** the *editor*! 
> Sweet work @hishboy*! 🎉🎉🎉*

**Comment by hishboy** [comment]
:) thank you!
